### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kalmarek** [kalmarek/2306.12358#1]
- [x] Prepare notebooks
 - [x] Prepare scripts
 - [x] some kind of ci (i.e. running scripts directly) (#2)
 - [x] link repo to a zenodo dataset (#4, https://github.com/kalmarek/2306.12358/pull/4/commits/666f92a305f63b2b902e6f0dc2e76b58fc697286)
 - [ ] figure out a way to redirect @infos from scripts to a file
 - [ ] create codeocean capsule (not really, unless the publisher pays for this @dawidkielak)

**Comment by kalmarek** [comment]
closing this as the remaining two points seem out of scope
